### ISSUE TITLE
TypeError: Module should export a function: nuxt-composition-api  

### ISSUE THREAD

**Issue by regenrek** [danielroe/nuxt-composition-api#7]
Hi 

I was looking in to the library today. Thank you for bringing this module to life.

### Problem:
 
It seems there are problems with the module initialization in nuxt.

### Solution
``` index.ts
const compositionApiModule: Module<any> = function () {
 // do something
}

export default compositionApiModule
```

**May I can add a PR - have fixed some parts.** 

Regards

**Comment by danielroe** [comment]
PRs are always welcome :-)

How are you importing this package?

**Comment by regenrek** [comment]
> PRs are always welcome 🙂
> 
> How are you importing this package? (It's not a Nuxt module.)

Well that explains it. Yes I tried to import i as module but failed. Anyway I just pushed an module approach for this package which includes @vue/composition-api too. 

https://github.com/danielroe/nuxt-composition-api/pull/9
